import { createClient } from '@supabase/supabase-js'
import { writeFileSync } from 'fs'
import { join } from 'path'

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!
const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY!

if (!supabaseServiceKey) {
  console.error('❌ SUPABASE_SERVICE_ROLE_KEY not set in .env.local')
  console.error('Get it from: https://app.supabase.com/project/tbwbaydyyjokrsjtgerh/settings/api')
  process.exit(1)
}

const supabase = createClient(supabaseUrl, supabaseServiceKey, {
  auth: {
    autoRefreshToken: false,
    persistSession: false,
  },
})

const TEST_USERS_TO_CREATE = [
  {
    name: 'alice',
    email: 'alice@test.tripthreads.com',
    full_name: 'Alice Johnson',
    password: 'test123456',
  },
  {
    name: 'benji',
    email: 'benji@test.tripthreads.com',
    full_name: 'Benji Williams',
    password: 'test123456',
  },
  {
    name: 'baylee',
    email: 'baylee@test.tripthreads.com',
    full_name: 'Baylee Davis',
    password: 'test123456',
  },
  {
    name: 'maya',
    email: 'maya@test.tripthreads.com',
    full_name: 'Maya Chen',
    password: 'test123456',
  },
]

async function createTestUsers() {
  console.log('🔧 Creating test users in Supabase...\n')

  const createdUsers: Record<
    string,
    { id: string; email: string; full_name: string; password: string }
  > = {}

  for (const user of TEST_USERS_TO_CREATE) {
    // Check if user already exists
    const { data: existingUser } = await supabase.auth.admin.listUsers()
    const existing = existingUser?.users.find(u => u.email === user.email)

    if (existing) {
      console.log(`✓ ${user.name} already exists: ${existing.id}`)
      createdUsers[user.name] = {
        id: existing.id,
        email: user.email,
        full_name: user.full_name,
        password: user.password,
      }
      continue
    }

    // Create new user
    const { data, error } = await supabase.auth.admin.createUser({
      email: user.email,
      password: user.password,
      email_confirm: true,
      user_metadata: {
        full_name: user.full_name,
      },
    })

    if (error) {
      console.error(`❌ Failed to create ${user.name}:`, error.message)
      continue
    }

    console.log(`✓ Created ${user.name}: ${data.user.id}`)
    createdUsers[user.name] = {
      id: data.user.id,
      email: user.email,
      full_name: user.full_name,
      password: user.password,
    }

    // Also create profile record
    const { error: profileError } = await supabase.from('profiles').upsert({
      id: data.user.id,
      email: user.email,
      full_name: user.full_name,
      updated_at: new Date().toISOString(),
    })

    if (profileError) {
      console.warn(`⚠️  Could not create profile for ${user.name}:`, profileError.message)
    }
  }

  // Generate updated fixture file
  const fixtureContent = `/**
 * Test User Fixtures
 *
 * AUTO-GENERATED by scripts/create-test-users.ts
 * Last updated: ${new Date().toISOString()}
 *
 * These are REAL users in the Supabase database for integration testing.
 */

export interface TestUser {
  id: string
  email: string
  full_name: string
  password: string
}

export const TEST_USERS = ${JSON.stringify(createdUsers, null, 2)} as const satisfies Record<string, TestUser>

// Export test user IDs for convenience
export const TEST_USER_IDS = {
  ${Object.entries(createdUsers)
    .map(([name]) => `${name}: TEST_USERS.${name}.id`)
    .join(',\n  ')}
} as const
`

  const fixturePath = join(__dirname, '../apps/web/tests/__fixtures__/test-users.ts')
  writeFileSync(fixturePath, fixtureContent, 'utf-8')

  console.log('\n✅ Test users created successfully!')
  console.log(`📝 Updated fixture file: ${fixturePath}`)
  console.log('\n💡 You can now run integration tests with: npm test')
}

createTestUsers().catch(console.error)
