/**
 * Test User Fixtures
 *
 * AUTO-GENERATED by scripts/create-test-users.ts
 * Last updated: 2025-12-09T16:22:49.316Z
 *
 * These are REAL users in the Supabase database for integration testing.
 */

export interface TestUser {
  id: string
  email: string
  full_name: string
  password: string
}

export const TEST_USERS = {
  alice: {
    id: 'cd1ac94d-54b7-4a4c-96ab-7c3eaf6da184',
    email: 'alice@test.tripthreads.com',
    full_name: 'Alice Johnson',
    password: 'test123456',
  },
  benji: {
    id: 'a3bdc626-16c7-47be-ab3d-31e27aa7164e',
    email: 'benji@test.tripthreads.com',
    full_name: 'Benji Williams',
    password: 'test123456',
  },
  baylee: {
    id: '6649c004-ca5f-4773-9f91-dcb4be64698a',
    email: 'baylee@test.tripthreads.com',
    full_name: 'Baylee Davis',
    password: 'test123456',
  },
  maya: {
    id: 'fc666afc-c24a-4805-b14f-d04115b53773',
    email: 'maya@test.tripthreads.com',
    full_name: 'Maya Chen',
    password: 'test123456',
  },
} as const satisfies Record<string, TestUser>

// Export test user IDs for convenience
export const TEST_USER_IDS = {
  alice: TEST_USERS.alice.id,
  benji: TEST_USERS.benji.id,
  baylee: TEST_USERS.baylee.id,
  maya: TEST_USERS.maya.id,
} as const
